# -*- coding: utf-8 -*-
"""pattern.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UDaGxI_VOkSs7WQwWkkcd3rHmYvH4GaM

**Pattern Programming**
"""

n= int(input("enter rows:"))
for i in range(n+1):
  for j in range(i):
    print("*",end=" ")
  print()

n= int(input("enter rows:"))
for i in range(n+1,0,-1):
  for j in range(i):
    print("*",end=" ")
  print()

n= int(input("enter rows:"))

for i in range(n+1):
  ch=1
  for j in range(i):
    print(ch,end=" ")
    ch=ch+1
  print()

n= int(input("enter rows:"))
ch=1
for i in range(n+1):
  for j in range(i):
    print(ch,end=" ")
    ch=ch+1
  print()

n= int(input("enter rows:"))
ch=(n-1)*(n-1)+1
for i in range(n+1):
  for j in range(i):
    print(ch,end=" ")
    ch=ch-1
  print()

from re import ASCII
n= int(input("enter rows:"))
ch="A"
for i in range(n+1):
  for j in range(i):
    print(ch,end=" ")
    ch=chr(ord(ch)+1)
  print()

n= int(input("enter rows:"))
for i in range(n+1):
  for j in range(n-i):
    print("  ",end=" ")
  for k in range(i*2-1):
    print("* ",end=" ")

  
  print()


n= int(input("enter rows:"))
s=(n-1)*(n-1)
ch=chr(s+65)
for i in range(n+1):
  for j in range(i):
    print(ch,end=" ")
    ch=chr(ord(ch)-1)
  print()

n= int(input("enter rows:"))
for i in range(n+1,0,-1):
  for j in range(n-i+1):
    print("  ",end=" ")
  for k in range(i*2-1):
    print("* ",end=" ")
  
  
  print()

n= int(input("please enter number:"))
for i in range(n):
  for j in range(n):
    if i==0 or i==n-1 or j==0 or j==n-1:
      print("* ",end=" ")
    else:
      print("  ",end=" ")
  print()

n= int(input("please enter number:"))
for i in range(1,n+1):
  for j in range(1,i+1):
    print(i*j,end=" ")
  print()