# -*- coding: utf-8 -*-
"""problem4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YGanvgeWVBDS7TdLevO2r-tSC3dXqK4v
"""



'''
Q.: take input from the user and check for the smallest/ least occurence of the character and show in the final output with its occurence
in case there is a tie , print any of the count of first character appearance

"user bangalore"

"u" has a count of 1
'''

n=input("enter string :")
dic={}
min=1000
mink=-1
for char in n:
  count=0
  for i in range(len(n)):
    if n[i]==char:
      occur=count+1
  dic[char]=occur
  if occur<min:
    mink=char
    min=occur

print("the {} has minimum count of {}".format(mink,min))