# -*- coding: utf-8 -*-
"""problem3_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p7hj71wcONog7LyOZA4wGzr_0CqfmUpP
"""



'''
Q.: create a function which takes an parameter of string type
    - accept the string in case if the string contains vowels(a,e,i,o,u)
    - accept the string in case if we have vowels in even position of data
'''

def strCheck(mystring):
  newstring=mystring.lower()
  if 'a' in newstring or 'e' in newstring or 'i' in newstring or 'o' in newstring or 'u' in newstring:
    print("String Accepted")
  else:
    print("not accepted")

mystring=input("enter a string :")
strCheck(mystring)

def strCheck(mystring):
  newstring=mystring.lower()
  flag=0
  for index in range(0,len(newstring),2):
    if 'a'== newstring[index] or 'e'==newstring[index] or 'i'== newstring[index] or 'o' == newstring[index] or 'u' == newstring[index]:
      pass
    else:
      flag=1
      break
  for index in range(1,len(newstring),2):
    if 'a'== newstring[index] or 'e'==newstring[index] or 'i'== newstring[index] or 'o' == newstring[index] or 'u' == newstring[index]:
      flag=1
      break
  
  if flag==1:
    print("String Rejected")
  else:  
    print("String accepted")


mystring=input("enter a string :")
strCheck(mystring)