# -*- coding: utf-8 -*-
"""problem3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BbAd8Htj9gTf9stvMi5z1huoaGUrwFEN
"""



'''
Q1. take an input from the user and check the data based on the following condition :
    the data should be of string data type 
    the length of the input should lie in the range from 6 to 15  character in length 
    the input should have at least 1 capital letter ( A to Z):
    1 smaller alphabet 
    1 number ( 0 - 9)
    1 special character (# @ $ %)

in case any of the condition is not valid ask for the input from the user upto 4 times , otherwise exit the program by putting a message input give is wrong
[Note]: we don't have to use any input library or using regular expression or re or isnumeric()or isalphabet() like this 


Q2. to launch an ec2 instance with python, (MAY USE -BOTO3 LIBRARY)
'''

flag=0
while(flag<5):
  flag=flag1=flag2=flag3=flag4=flag5=0
  n=input("enter a string :")
  if len(n)>=6 and len(n)<=15:
    flag1=1
  for ch in n:
    if ord(ch)>=65 and ord(ch)<=90:
      flag2=1
    if ord(ch)>=97 and ord(ch)<=122:
      flag3=1
    if ord(ch)>=48 and ord(ch)<57 :
      flag4=1
    if (ord(ch)>=35 and ord(ch)<=38) or ord(ch)==64 :
      flag5=1
  flag=flag1+flag2+flag3+flag4+flag5
  if flag==5:
    print("Entered string accepted")