# -*- coding: utf-8 -*-
"""problem3_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14qoaQ3tDaEuAshgh1-FTtNkWWpRaihI6
"""

'''
Create a lambda function to get the table of any number
2
4
6
8
10
'''

'''
create a lambda function to get the table of any number
'''

st="\n".join(list(map(lambda x: str(2*x),range(1,11))))
print(st,type(st))

num = [int(input("Enter a number: "))]


# let's create our lambda function for the table
table = list(map(lambda x, y: x * y, list(range(1, 11)), num *10))

print(table)