# -*- coding: utf-8 -*-
"""problem3_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pfUcVDPRq5BXRnMDO3KfCNfNl0BbdSsg
"""



'''
to swap two numbers without using 3rd variable
'''

x=10
y=20

x=x+y
y=x-y
x=x-y

print(x,y)