# -*- coding: utf-8 -*-
"""problem3_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vv2GWUj6ha-sGwoBW25vvYG2egIhqW_P
"""

'''
program to find LCM of n Numbers
'''

def find_gcd(x, y):
    while(y):
        x, y = y, x % y
    return x

'''
program to find LCM of n numbers
'''

def find_lcm(n,*args):
  mylist=list(args)[0]
  mul=1
  for val in mylist:
    mul=mul*val
  return mul/n

x=input("enter values :")
x=x.split(",")
x=[int(val) for val in x]
gcd=find_gcd(x[0],x[1])
for i in range(2,len(x)):
  gcd=find_gcd(gcd,x[i])
print("GCD is :",gcd)
lcm=find_lcm(gcd,x)
print("LCM is :",lcm)