# -*- coding: utf-8 -*-
"""problem1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v68BcHQN6QTDcTqunPxp1GmxtJxDv6zi
"""



'''
Q. take 2 numbers as a input from user , if numbers are integer than perform the arithmetic operation otherwise ask for input again
'''

def isfloat(num):
    try:
        float(num)
        return True
    except ValueError:
        return False
n1= " "
while (type(n1) is str):
  n1= input("enter first number:")
  if n1.isdigit():
    n1=int(n1)
  elif isfloat(n1):
    n1=float(n1)
    
  
n2= " "
while (type(n2) is str):
  n2= input("enter second number:")
  if n2.isdigit():
    n2=int(n2)
  elif isfloat(n2):
    n2=float(n2)
print("sum is :",n1+n2)