# -*- coding: utf-8 -*-
"""problem2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AAn0QfSTgOs2rf0AIiq6MbsL-IacO4BX
"""



# for loop

# range method - we pass a value 

'''
Q: take a string from a user , in case if you find out any character in repetition together , then we need to delete it .


'''

new_st=""
pr=""
for i in range(len(st)):
  count=0
  for j in range(i+1,len(st)):
   # print(i,st[i],j,st[j])
    if st[i]==st[j]:
      count=count+1
      pr=st[i]
    else:
      break
  if count<1 and pr!=st[i]:
    new_st=new_st + st[i]
print(new_st)