# -*- coding: utf-8 -*-
"""python6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fcqbtqd-q90_iymGsjud7RgLc4nWresp
"""



'''
Q: take an input string from user and return all the unique words from the string 

Input="hey user hey tushar hey hope  you are well"
output= "hey user tushar hope you are well"


'''

n="hey user hey tushar hey hope you are well"
mylist=n.split(" ")
newlist=[]
print(mylist)
for val in mylist:
  if val not in newlist:
    newlist.append(val)   
print(" ".join(newlist))